/*
CrawlSnap API

CrawlSnap is a data intelligence platform. It delivers structured, on-demand data through fast, typed HTTP APIs you can call from any language. This reference covers authentication, the response envelope, error handling, and the available CrawlSnap data products:    - **VectorSnap** — reputation, detections, categories, and relationships     for url / hash / ip / domain.   - **PulseSnap** — threat-intelligence pulse (and sandbox) enrichment for     url / hash / ip / domain.   - **SubdoSnap** — paginated subdomain enumeration for a domain.  ## Authentication  Authenticate every request with your CrawlSnap API key, sent as a Bearer token in the `Authorization` header:      Authorization: Bearer sk-cs-...  Create and rotate keys from your dashboard. Treat the key like a password: it carries your full quota and must stay secret. Never embed it in client-side code or commit it to source control.  ## Response envelope  Every response — success or error — uses the same envelope:  ```json {   \"data\": { ... },          // payload on success, null on failure   \"is_success\": true,        // authoritative success flag   \"message\": \"Success\",     // human-readable summary   \"response_code\": 200       // mirrors the HTTP status code } ```  Always check `is_success` before reading `data`.  ## Status codes  HTTP status codes follow standard REST semantics; the body `response_code` mirrors the HTTP status.    - **200** — success, `data` populated.   - **400** — invalid input (malformed URL / hash / IP / domain).   - **401** — missing or invalid API key.   - **402** — out of credits, or monthly quota exceeded.   - **403** — subscription is not active.   - **404** — no IoC data found for the supplied indicator.   - **429** — daily request limit exceeded.   - **5xx** — server error, or the upstream enrichment service was     unavailable / timed out.

API version: 1.0.0
Contact: support@crawlsnap.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IocHashScanData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IocHashScanData{}

// IocHashScanData struct for IocHashScanData
type IocHashScanData struct {
	// SHA-256 of the queried hash (resolved upstream when md5/sha1 supplied).
	HashId          string   `json:"hash_id"`
	SearchType      string   `json:"search_type"`
	Ssdeep          *string  `json:"ssdeep,omitempty"`
	TypeTag         *string  `json:"type_tag,omitempty"`
	TypeTags        []string `json:"type_tags,omitempty"`
	Magic           *string  `json:"magic,omitempty"`
	Magika          *string  `json:"magika,omitempty"`
	TypeDescription *string  `json:"type_description,omitempty"`
	MeaningfulName  *string  `json:"meaningful_name,omitempty"`
	Authentihash    *string  `json:"authentihash,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	Detectiteasy     interface{}              `json:"detectiteasy,omitempty"`
	Trid             []map[string]interface{} `json:"trid,omitempty"`
	TypeExtension    *string                  `json:"type_extension,omitempty"`
	Tags             []string                 `json:"tags,omitempty"`
	Tlsh             *string                  `json:"tlsh,omitempty"`
	AnalysisDate     *int64                   `json:"analysis_date,omitempty"`
	ModificationDate *int64                   `json:"modification_date,omitempty"`
	Md5              *string                  `json:"md5,omitempty"`
	Sha1             *string                  `json:"sha1,omitempty"`
	Sha256           *string                  `json:"sha256,omitempty"`
	FileSize         *int64                   `json:"file_size,omitempty"`
	DroppedFiles     []map[string]interface{} `json:"dropped_files,omitempty"`
	BundledFiles     []map[string]interface{} `json:"bundled_files,omitempty"`
	ContactedIps     []map[string]interface{} `json:"contacted_ips,omitempty"`
	ContactedDomains []map[string]interface{} `json:"contacted_domains,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	Sigma interface{} `json:"sigma,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	SigmaStats interface{} `json:"sigma_stats,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	Classification interface{} `json:"classification,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	PeInfo interface{} `json:"pe_info,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	Signature interface{} `json:"signature,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	VotesResult interface{} `json:"votes_result,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	SandboxVerdicts interface{} `json:"sandbox_verdicts,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	SecurityVendorAnalysis interface{} `json:"security_vendor_analysis,omitempty"`
	// Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.
	SecurityVendorAnalysisStats interface{} `json:"security_vendor_analysis_stats,omitempty"`
}

type _IocHashScanData IocHashScanData

// NewIocHashScanData instantiates a new IocHashScanData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIocHashScanData(hashId string, searchType string) *IocHashScanData {
	this := IocHashScanData{}
	this.HashId = hashId
	this.SearchType = searchType
	return &this
}

// NewIocHashScanDataWithDefaults instantiates a new IocHashScanData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIocHashScanDataWithDefaults() *IocHashScanData {
	this := IocHashScanData{}
	return &this
}

// GetHashId returns the HashId field value
func (o *IocHashScanData) GetHashId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HashId
}

// GetHashIdOk returns a tuple with the HashId field value
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetHashIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashId, true
}

// SetHashId sets field value
func (o *IocHashScanData) SetHashId(v string) {
	o.HashId = v
}

// GetSearchType returns the SearchType field value
func (o *IocHashScanData) GetSearchType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SearchType
}

// GetSearchTypeOk returns a tuple with the SearchType field value
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetSearchTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SearchType, true
}

// SetSearchType sets field value
func (o *IocHashScanData) SetSearchType(v string) {
	o.SearchType = v
}

// GetSsdeep returns the Ssdeep field value if set, zero value otherwise.
func (o *IocHashScanData) GetSsdeep() string {
	if o == nil || IsNil(o.Ssdeep) {
		var ret string
		return ret
	}
	return *o.Ssdeep
}

// GetSsdeepOk returns a tuple with the Ssdeep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetSsdeepOk() (*string, bool) {
	if o == nil || IsNil(o.Ssdeep) {
		return nil, false
	}
	return o.Ssdeep, true
}

// HasSsdeep returns a boolean if a field has been set.
func (o *IocHashScanData) HasSsdeep() bool {
	if o != nil && !IsNil(o.Ssdeep) {
		return true
	}

	return false
}

// SetSsdeep gets a reference to the given string and assigns it to the Ssdeep field.
func (o *IocHashScanData) SetSsdeep(v string) {
	o.Ssdeep = &v
}

// GetTypeTag returns the TypeTag field value if set, zero value otherwise.
func (o *IocHashScanData) GetTypeTag() string {
	if o == nil || IsNil(o.TypeTag) {
		var ret string
		return ret
	}
	return *o.TypeTag
}

// GetTypeTagOk returns a tuple with the TypeTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTypeTagOk() (*string, bool) {
	if o == nil || IsNil(o.TypeTag) {
		return nil, false
	}
	return o.TypeTag, true
}

// HasTypeTag returns a boolean if a field has been set.
func (o *IocHashScanData) HasTypeTag() bool {
	if o != nil && !IsNil(o.TypeTag) {
		return true
	}

	return false
}

// SetTypeTag gets a reference to the given string and assigns it to the TypeTag field.
func (o *IocHashScanData) SetTypeTag(v string) {
	o.TypeTag = &v
}

// GetTypeTags returns the TypeTags field value if set, zero value otherwise.
func (o *IocHashScanData) GetTypeTags() []string {
	if o == nil || IsNil(o.TypeTags) {
		var ret []string
		return ret
	}
	return o.TypeTags
}

// GetTypeTagsOk returns a tuple with the TypeTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTypeTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.TypeTags) {
		return nil, false
	}
	return o.TypeTags, true
}

// HasTypeTags returns a boolean if a field has been set.
func (o *IocHashScanData) HasTypeTags() bool {
	if o != nil && !IsNil(o.TypeTags) {
		return true
	}

	return false
}

// SetTypeTags gets a reference to the given []string and assigns it to the TypeTags field.
func (o *IocHashScanData) SetTypeTags(v []string) {
	o.TypeTags = v
}

// GetMagic returns the Magic field value if set, zero value otherwise.
func (o *IocHashScanData) GetMagic() string {
	if o == nil || IsNil(o.Magic) {
		var ret string
		return ret
	}
	return *o.Magic
}

// GetMagicOk returns a tuple with the Magic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetMagicOk() (*string, bool) {
	if o == nil || IsNil(o.Magic) {
		return nil, false
	}
	return o.Magic, true
}

// HasMagic returns a boolean if a field has been set.
func (o *IocHashScanData) HasMagic() bool {
	if o != nil && !IsNil(o.Magic) {
		return true
	}

	return false
}

// SetMagic gets a reference to the given string and assigns it to the Magic field.
func (o *IocHashScanData) SetMagic(v string) {
	o.Magic = &v
}

// GetMagika returns the Magika field value if set, zero value otherwise.
func (o *IocHashScanData) GetMagika() string {
	if o == nil || IsNil(o.Magika) {
		var ret string
		return ret
	}
	return *o.Magika
}

// GetMagikaOk returns a tuple with the Magika field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetMagikaOk() (*string, bool) {
	if o == nil || IsNil(o.Magika) {
		return nil, false
	}
	return o.Magika, true
}

// HasMagika returns a boolean if a field has been set.
func (o *IocHashScanData) HasMagika() bool {
	if o != nil && !IsNil(o.Magika) {
		return true
	}

	return false
}

// SetMagika gets a reference to the given string and assigns it to the Magika field.
func (o *IocHashScanData) SetMagika(v string) {
	o.Magika = &v
}

// GetTypeDescription returns the TypeDescription field value if set, zero value otherwise.
func (o *IocHashScanData) GetTypeDescription() string {
	if o == nil || IsNil(o.TypeDescription) {
		var ret string
		return ret
	}
	return *o.TypeDescription
}

// GetTypeDescriptionOk returns a tuple with the TypeDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTypeDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeDescription) {
		return nil, false
	}
	return o.TypeDescription, true
}

// HasTypeDescription returns a boolean if a field has been set.
func (o *IocHashScanData) HasTypeDescription() bool {
	if o != nil && !IsNil(o.TypeDescription) {
		return true
	}

	return false
}

// SetTypeDescription gets a reference to the given string and assigns it to the TypeDescription field.
func (o *IocHashScanData) SetTypeDescription(v string) {
	o.TypeDescription = &v
}

// GetMeaningfulName returns the MeaningfulName field value if set, zero value otherwise.
func (o *IocHashScanData) GetMeaningfulName() string {
	if o == nil || IsNil(o.MeaningfulName) {
		var ret string
		return ret
	}
	return *o.MeaningfulName
}

// GetMeaningfulNameOk returns a tuple with the MeaningfulName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetMeaningfulNameOk() (*string, bool) {
	if o == nil || IsNil(o.MeaningfulName) {
		return nil, false
	}
	return o.MeaningfulName, true
}

// HasMeaningfulName returns a boolean if a field has been set.
func (o *IocHashScanData) HasMeaningfulName() bool {
	if o != nil && !IsNil(o.MeaningfulName) {
		return true
	}

	return false
}

// SetMeaningfulName gets a reference to the given string and assigns it to the MeaningfulName field.
func (o *IocHashScanData) SetMeaningfulName(v string) {
	o.MeaningfulName = &v
}

// GetAuthentihash returns the Authentihash field value if set, zero value otherwise.
func (o *IocHashScanData) GetAuthentihash() string {
	if o == nil || IsNil(o.Authentihash) {
		var ret string
		return ret
	}
	return *o.Authentihash
}

// GetAuthentihashOk returns a tuple with the Authentihash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetAuthentihashOk() (*string, bool) {
	if o == nil || IsNil(o.Authentihash) {
		return nil, false
	}
	return o.Authentihash, true
}

// HasAuthentihash returns a boolean if a field has been set.
func (o *IocHashScanData) HasAuthentihash() bool {
	if o != nil && !IsNil(o.Authentihash) {
		return true
	}

	return false
}

// SetAuthentihash gets a reference to the given string and assigns it to the Authentihash field.
func (o *IocHashScanData) SetAuthentihash(v string) {
	o.Authentihash = &v
}

// GetDetectiteasy returns the Detectiteasy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetDetectiteasy() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Detectiteasy
}

// GetDetectiteasyOk returns a tuple with the Detectiteasy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetDetectiteasyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Detectiteasy) {
		return nil, false
	}
	return &o.Detectiteasy, true
}

// HasDetectiteasy returns a boolean if a field has been set.
func (o *IocHashScanData) HasDetectiteasy() bool {
	if o != nil && !IsNil(o.Detectiteasy) {
		return true
	}

	return false
}

// SetDetectiteasy gets a reference to the given interface{} and assigns it to the Detectiteasy field.
func (o *IocHashScanData) SetDetectiteasy(v interface{}) {
	o.Detectiteasy = v
}

// GetTrid returns the Trid field value if set, zero value otherwise.
func (o *IocHashScanData) GetTrid() []map[string]interface{} {
	if o == nil || IsNil(o.Trid) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Trid
}

// GetTridOk returns a tuple with the Trid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTridOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Trid) {
		return nil, false
	}
	return o.Trid, true
}

// HasTrid returns a boolean if a field has been set.
func (o *IocHashScanData) HasTrid() bool {
	if o != nil && !IsNil(o.Trid) {
		return true
	}

	return false
}

// SetTrid gets a reference to the given []map[string]interface{} and assigns it to the Trid field.
func (o *IocHashScanData) SetTrid(v []map[string]interface{}) {
	o.Trid = v
}

// GetTypeExtension returns the TypeExtension field value if set, zero value otherwise.
func (o *IocHashScanData) GetTypeExtension() string {
	if o == nil || IsNil(o.TypeExtension) {
		var ret string
		return ret
	}
	return *o.TypeExtension
}

// GetTypeExtensionOk returns a tuple with the TypeExtension field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTypeExtensionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeExtension) {
		return nil, false
	}
	return o.TypeExtension, true
}

// HasTypeExtension returns a boolean if a field has been set.
func (o *IocHashScanData) HasTypeExtension() bool {
	if o != nil && !IsNil(o.TypeExtension) {
		return true
	}

	return false
}

// SetTypeExtension gets a reference to the given string and assigns it to the TypeExtension field.
func (o *IocHashScanData) SetTypeExtension(v string) {
	o.TypeExtension = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *IocHashScanData) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *IocHashScanData) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *IocHashScanData) SetTags(v []string) {
	o.Tags = v
}

// GetTlsh returns the Tlsh field value if set, zero value otherwise.
func (o *IocHashScanData) GetTlsh() string {
	if o == nil || IsNil(o.Tlsh) {
		var ret string
		return ret
	}
	return *o.Tlsh
}

// GetTlshOk returns a tuple with the Tlsh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetTlshOk() (*string, bool) {
	if o == nil || IsNil(o.Tlsh) {
		return nil, false
	}
	return o.Tlsh, true
}

// HasTlsh returns a boolean if a field has been set.
func (o *IocHashScanData) HasTlsh() bool {
	if o != nil && !IsNil(o.Tlsh) {
		return true
	}

	return false
}

// SetTlsh gets a reference to the given string and assigns it to the Tlsh field.
func (o *IocHashScanData) SetTlsh(v string) {
	o.Tlsh = &v
}

// GetAnalysisDate returns the AnalysisDate field value if set, zero value otherwise.
func (o *IocHashScanData) GetAnalysisDate() int64 {
	if o == nil || IsNil(o.AnalysisDate) {
		var ret int64
		return ret
	}
	return *o.AnalysisDate
}

// GetAnalysisDateOk returns a tuple with the AnalysisDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetAnalysisDateOk() (*int64, bool) {
	if o == nil || IsNil(o.AnalysisDate) {
		return nil, false
	}
	return o.AnalysisDate, true
}

// HasAnalysisDate returns a boolean if a field has been set.
func (o *IocHashScanData) HasAnalysisDate() bool {
	if o != nil && !IsNil(o.AnalysisDate) {
		return true
	}

	return false
}

// SetAnalysisDate gets a reference to the given int64 and assigns it to the AnalysisDate field.
func (o *IocHashScanData) SetAnalysisDate(v int64) {
	o.AnalysisDate = &v
}

// GetModificationDate returns the ModificationDate field value if set, zero value otherwise.
func (o *IocHashScanData) GetModificationDate() int64 {
	if o == nil || IsNil(o.ModificationDate) {
		var ret int64
		return ret
	}
	return *o.ModificationDate
}

// GetModificationDateOk returns a tuple with the ModificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetModificationDateOk() (*int64, bool) {
	if o == nil || IsNil(o.ModificationDate) {
		return nil, false
	}
	return o.ModificationDate, true
}

// HasModificationDate returns a boolean if a field has been set.
func (o *IocHashScanData) HasModificationDate() bool {
	if o != nil && !IsNil(o.ModificationDate) {
		return true
	}

	return false
}

// SetModificationDate gets a reference to the given int64 and assigns it to the ModificationDate field.
func (o *IocHashScanData) SetModificationDate(v int64) {
	o.ModificationDate = &v
}

// GetMd5 returns the Md5 field value if set, zero value otherwise.
func (o *IocHashScanData) GetMd5() string {
	if o == nil || IsNil(o.Md5) {
		var ret string
		return ret
	}
	return *o.Md5
}

// GetMd5Ok returns a tuple with the Md5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetMd5Ok() (*string, bool) {
	if o == nil || IsNil(o.Md5) {
		return nil, false
	}
	return o.Md5, true
}

// HasMd5 returns a boolean if a field has been set.
func (o *IocHashScanData) HasMd5() bool {
	if o != nil && !IsNil(o.Md5) {
		return true
	}

	return false
}

// SetMd5 gets a reference to the given string and assigns it to the Md5 field.
func (o *IocHashScanData) SetMd5(v string) {
	o.Md5 = &v
}

// GetSha1 returns the Sha1 field value if set, zero value otherwise.
func (o *IocHashScanData) GetSha1() string {
	if o == nil || IsNil(o.Sha1) {
		var ret string
		return ret
	}
	return *o.Sha1
}

// GetSha1Ok returns a tuple with the Sha1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetSha1Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha1) {
		return nil, false
	}
	return o.Sha1, true
}

// HasSha1 returns a boolean if a field has been set.
func (o *IocHashScanData) HasSha1() bool {
	if o != nil && !IsNil(o.Sha1) {
		return true
	}

	return false
}

// SetSha1 gets a reference to the given string and assigns it to the Sha1 field.
func (o *IocHashScanData) SetSha1(v string) {
	o.Sha1 = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *IocHashScanData) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *IocHashScanData) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *IocHashScanData) SetSha256(v string) {
	o.Sha256 = &v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *IocHashScanData) GetFileSize() int64 {
	if o == nil || IsNil(o.FileSize) {
		var ret int64
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetFileSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *IocHashScanData) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int64 and assigns it to the FileSize field.
func (o *IocHashScanData) SetFileSize(v int64) {
	o.FileSize = &v
}

// GetDroppedFiles returns the DroppedFiles field value if set, zero value otherwise.
func (o *IocHashScanData) GetDroppedFiles() []map[string]interface{} {
	if o == nil || IsNil(o.DroppedFiles) {
		var ret []map[string]interface{}
		return ret
	}
	return o.DroppedFiles
}

// GetDroppedFilesOk returns a tuple with the DroppedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetDroppedFilesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.DroppedFiles) {
		return nil, false
	}
	return o.DroppedFiles, true
}

// HasDroppedFiles returns a boolean if a field has been set.
func (o *IocHashScanData) HasDroppedFiles() bool {
	if o != nil && !IsNil(o.DroppedFiles) {
		return true
	}

	return false
}

// SetDroppedFiles gets a reference to the given []map[string]interface{} and assigns it to the DroppedFiles field.
func (o *IocHashScanData) SetDroppedFiles(v []map[string]interface{}) {
	o.DroppedFiles = v
}

// GetBundledFiles returns the BundledFiles field value if set, zero value otherwise.
func (o *IocHashScanData) GetBundledFiles() []map[string]interface{} {
	if o == nil || IsNil(o.BundledFiles) {
		var ret []map[string]interface{}
		return ret
	}
	return o.BundledFiles
}

// GetBundledFilesOk returns a tuple with the BundledFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetBundledFilesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.BundledFiles) {
		return nil, false
	}
	return o.BundledFiles, true
}

// HasBundledFiles returns a boolean if a field has been set.
func (o *IocHashScanData) HasBundledFiles() bool {
	if o != nil && !IsNil(o.BundledFiles) {
		return true
	}

	return false
}

// SetBundledFiles gets a reference to the given []map[string]interface{} and assigns it to the BundledFiles field.
func (o *IocHashScanData) SetBundledFiles(v []map[string]interface{}) {
	o.BundledFiles = v
}

// GetContactedIps returns the ContactedIps field value if set, zero value otherwise.
func (o *IocHashScanData) GetContactedIps() []map[string]interface{} {
	if o == nil || IsNil(o.ContactedIps) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ContactedIps
}

// GetContactedIpsOk returns a tuple with the ContactedIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetContactedIpsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ContactedIps) {
		return nil, false
	}
	return o.ContactedIps, true
}

// HasContactedIps returns a boolean if a field has been set.
func (o *IocHashScanData) HasContactedIps() bool {
	if o != nil && !IsNil(o.ContactedIps) {
		return true
	}

	return false
}

// SetContactedIps gets a reference to the given []map[string]interface{} and assigns it to the ContactedIps field.
func (o *IocHashScanData) SetContactedIps(v []map[string]interface{}) {
	o.ContactedIps = v
}

// GetContactedDomains returns the ContactedDomains field value if set, zero value otherwise.
func (o *IocHashScanData) GetContactedDomains() []map[string]interface{} {
	if o == nil || IsNil(o.ContactedDomains) {
		var ret []map[string]interface{}
		return ret
	}
	return o.ContactedDomains
}

// GetContactedDomainsOk returns a tuple with the ContactedDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IocHashScanData) GetContactedDomainsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ContactedDomains) {
		return nil, false
	}
	return o.ContactedDomains, true
}

// HasContactedDomains returns a boolean if a field has been set.
func (o *IocHashScanData) HasContactedDomains() bool {
	if o != nil && !IsNil(o.ContactedDomains) {
		return true
	}

	return false
}

// SetContactedDomains gets a reference to the given []map[string]interface{} and assigns it to the ContactedDomains field.
func (o *IocHashScanData) SetContactedDomains(v []map[string]interface{}) {
	o.ContactedDomains = v
}

// GetSigma returns the Sigma field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetSigma() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Sigma
}

// GetSigmaOk returns a tuple with the Sigma field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetSigmaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Sigma) {
		return nil, false
	}
	return &o.Sigma, true
}

// HasSigma returns a boolean if a field has been set.
func (o *IocHashScanData) HasSigma() bool {
	if o != nil && !IsNil(o.Sigma) {
		return true
	}

	return false
}

// SetSigma gets a reference to the given interface{} and assigns it to the Sigma field.
func (o *IocHashScanData) SetSigma(v interface{}) {
	o.Sigma = v
}

// GetSigmaStats returns the SigmaStats field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetSigmaStats() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SigmaStats
}

// GetSigmaStatsOk returns a tuple with the SigmaStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetSigmaStatsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SigmaStats) {
		return nil, false
	}
	return &o.SigmaStats, true
}

// HasSigmaStats returns a boolean if a field has been set.
func (o *IocHashScanData) HasSigmaStats() bool {
	if o != nil && !IsNil(o.SigmaStats) {
		return true
	}

	return false
}

// SetSigmaStats gets a reference to the given interface{} and assigns it to the SigmaStats field.
func (o *IocHashScanData) SetSigmaStats(v interface{}) {
	o.SigmaStats = v
}

// GetClassification returns the Classification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetClassification() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetClassificationOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Classification) {
		return nil, false
	}
	return &o.Classification, true
}

// HasClassification returns a boolean if a field has been set.
func (o *IocHashScanData) HasClassification() bool {
	if o != nil && !IsNil(o.Classification) {
		return true
	}

	return false
}

// SetClassification gets a reference to the given interface{} and assigns it to the Classification field.
func (o *IocHashScanData) SetClassification(v interface{}) {
	o.Classification = v
}

// GetPeInfo returns the PeInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetPeInfo() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PeInfo
}

// GetPeInfoOk returns a tuple with the PeInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetPeInfoOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PeInfo) {
		return nil, false
	}
	return &o.PeInfo, true
}

// HasPeInfo returns a boolean if a field has been set.
func (o *IocHashScanData) HasPeInfo() bool {
	if o != nil && !IsNil(o.PeInfo) {
		return true
	}

	return false
}

// SetPeInfo gets a reference to the given interface{} and assigns it to the PeInfo field.
func (o *IocHashScanData) SetPeInfo(v interface{}) {
	o.PeInfo = v
}

// GetSignature returns the Signature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetSignature() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetSignatureOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return &o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *IocHashScanData) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given interface{} and assigns it to the Signature field.
func (o *IocHashScanData) SetSignature(v interface{}) {
	o.Signature = v
}

// GetVotesResult returns the VotesResult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetVotesResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.VotesResult
}

// GetVotesResultOk returns a tuple with the VotesResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetVotesResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.VotesResult) {
		return nil, false
	}
	return &o.VotesResult, true
}

// HasVotesResult returns a boolean if a field has been set.
func (o *IocHashScanData) HasVotesResult() bool {
	if o != nil && !IsNil(o.VotesResult) {
		return true
	}

	return false
}

// SetVotesResult gets a reference to the given interface{} and assigns it to the VotesResult field.
func (o *IocHashScanData) SetVotesResult(v interface{}) {
	o.VotesResult = v
}

// GetSandboxVerdicts returns the SandboxVerdicts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetSandboxVerdicts() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SandboxVerdicts
}

// GetSandboxVerdictsOk returns a tuple with the SandboxVerdicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetSandboxVerdictsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SandboxVerdicts) {
		return nil, false
	}
	return &o.SandboxVerdicts, true
}

// HasSandboxVerdicts returns a boolean if a field has been set.
func (o *IocHashScanData) HasSandboxVerdicts() bool {
	if o != nil && !IsNil(o.SandboxVerdicts) {
		return true
	}

	return false
}

// SetSandboxVerdicts gets a reference to the given interface{} and assigns it to the SandboxVerdicts field.
func (o *IocHashScanData) SetSandboxVerdicts(v interface{}) {
	o.SandboxVerdicts = v
}

// GetSecurityVendorAnalysis returns the SecurityVendorAnalysis field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetSecurityVendorAnalysis() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SecurityVendorAnalysis
}

// GetSecurityVendorAnalysisOk returns a tuple with the SecurityVendorAnalysis field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetSecurityVendorAnalysisOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SecurityVendorAnalysis) {
		return nil, false
	}
	return &o.SecurityVendorAnalysis, true
}

// HasSecurityVendorAnalysis returns a boolean if a field has been set.
func (o *IocHashScanData) HasSecurityVendorAnalysis() bool {
	if o != nil && !IsNil(o.SecurityVendorAnalysis) {
		return true
	}

	return false
}

// SetSecurityVendorAnalysis gets a reference to the given interface{} and assigns it to the SecurityVendorAnalysis field.
func (o *IocHashScanData) SetSecurityVendorAnalysis(v interface{}) {
	o.SecurityVendorAnalysis = v
}

// GetSecurityVendorAnalysisStats returns the SecurityVendorAnalysisStats field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IocHashScanData) GetSecurityVendorAnalysisStats() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SecurityVendorAnalysisStats
}

// GetSecurityVendorAnalysisStatsOk returns a tuple with the SecurityVendorAnalysisStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IocHashScanData) GetSecurityVendorAnalysisStatsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SecurityVendorAnalysisStats) {
		return nil, false
	}
	return &o.SecurityVendorAnalysisStats, true
}

// HasSecurityVendorAnalysisStats returns a boolean if a field has been set.
func (o *IocHashScanData) HasSecurityVendorAnalysisStats() bool {
	if o != nil && !IsNil(o.SecurityVendorAnalysisStats) {
		return true
	}

	return false
}

// SetSecurityVendorAnalysisStats gets a reference to the given interface{} and assigns it to the SecurityVendorAnalysisStats field.
func (o *IocHashScanData) SetSecurityVendorAnalysisStats(v interface{}) {
	o.SecurityVendorAnalysisStats = v
}

func (o IocHashScanData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IocHashScanData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hash_id"] = o.HashId
	toSerialize["search_type"] = o.SearchType
	if !IsNil(o.Ssdeep) {
		toSerialize["ssdeep"] = o.Ssdeep
	}
	if !IsNil(o.TypeTag) {
		toSerialize["type_tag"] = o.TypeTag
	}
	if !IsNil(o.TypeTags) {
		toSerialize["type_tags"] = o.TypeTags
	}
	if !IsNil(o.Magic) {
		toSerialize["magic"] = o.Magic
	}
	if !IsNil(o.Magika) {
		toSerialize["magika"] = o.Magika
	}
	if !IsNil(o.TypeDescription) {
		toSerialize["type_description"] = o.TypeDescription
	}
	if !IsNil(o.MeaningfulName) {
		toSerialize["meaningful_name"] = o.MeaningfulName
	}
	if !IsNil(o.Authentihash) {
		toSerialize["authentihash"] = o.Authentihash
	}
	if o.Detectiteasy != nil {
		toSerialize["detectiteasy"] = o.Detectiteasy
	}
	if !IsNil(o.Trid) {
		toSerialize["trid"] = o.Trid
	}
	if !IsNil(o.TypeExtension) {
		toSerialize["type_extension"] = o.TypeExtension
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Tlsh) {
		toSerialize["tlsh"] = o.Tlsh
	}
	if !IsNil(o.AnalysisDate) {
		toSerialize["analysis_date"] = o.AnalysisDate
	}
	if !IsNil(o.ModificationDate) {
		toSerialize["modification_date"] = o.ModificationDate
	}
	if !IsNil(o.Md5) {
		toSerialize["md5"] = o.Md5
	}
	if !IsNil(o.Sha1) {
		toSerialize["sha1"] = o.Sha1
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	if !IsNil(o.DroppedFiles) {
		toSerialize["dropped_files"] = o.DroppedFiles
	}
	if !IsNil(o.BundledFiles) {
		toSerialize["bundled_files"] = o.BundledFiles
	}
	if !IsNil(o.ContactedIps) {
		toSerialize["contacted_ips"] = o.ContactedIps
	}
	if !IsNil(o.ContactedDomains) {
		toSerialize["contacted_domains"] = o.ContactedDomains
	}
	if o.Sigma != nil {
		toSerialize["sigma"] = o.Sigma
	}
	if o.SigmaStats != nil {
		toSerialize["sigma_stats"] = o.SigmaStats
	}
	if o.Classification != nil {
		toSerialize["classification"] = o.Classification
	}
	if o.PeInfo != nil {
		toSerialize["pe_info"] = o.PeInfo
	}
	if o.Signature != nil {
		toSerialize["signature"] = o.Signature
	}
	if o.VotesResult != nil {
		toSerialize["votes_result"] = o.VotesResult
	}
	if o.SandboxVerdicts != nil {
		toSerialize["sandbox_verdicts"] = o.SandboxVerdicts
	}
	if o.SecurityVendorAnalysis != nil {
		toSerialize["security_vendor_analysis"] = o.SecurityVendorAnalysis
	}
	if o.SecurityVendorAnalysisStats != nil {
		toSerialize["security_vendor_analysis_stats"] = o.SecurityVendorAnalysisStats
	}
	return toSerialize, nil
}

func (o *IocHashScanData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hash_id",
		"search_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIocHashScanData := _IocHashScanData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIocHashScanData)

	if err != nil {
		return err
	}

	*o = IocHashScanData(varIocHashScanData)

	return err
}

type NullableIocHashScanData struct {
	value *IocHashScanData
	isSet bool
}

func (v NullableIocHashScanData) Get() *IocHashScanData {
	return v.value
}

func (v *NullableIocHashScanData) Set(val *IocHashScanData) {
	v.value = val
	v.isSet = true
}

func (v NullableIocHashScanData) IsSet() bool {
	return v.isSet
}

func (v *NullableIocHashScanData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIocHashScanData(val *IocHashScanData) *NullableIocHashScanData {
	return &NullableIocHashScanData{value: val, isSet: true}
}

func (v NullableIocHashScanData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIocHashScanData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
